[arm]
HOSTNAME = localhost
BINARY = gnunet-service-arm
ACCEPT_FROM = 127.0.0.1;
ACCEPT_FROM6 = ::1;
UNIXPATH = $GNUNET_USER_RUNTIME_DIR/gnunet-service-arm.sock
UNIX_MATCH_UID = YES
UNIX_MATCH_GID = YES
GLOBAL_PREFIX = 
OPTIONS = -l $GNUNET_CACHE_HOME/gnunet-%Y-%m-%d.log
CONFIG = /home/gnunet21/gnunet.conf

[nat]
START_ON_DEMAND = YES
HOSTNAME = localhost
BINARY = gnunet-service-nat
ACCEPT_FROM = 127.0.0.1;
ACCEPT_FROM6 = ::1;
UNIXPATH = $GNUNET_RUNTIME_DIR/gnunet-service-nat.sock
UNIX_MATCH_UID = YES
UNIX_MATCH_GID = YES
ENABLE_UPNP = YES
ENABLE_IPSCAN = YES
DISABLEV6 = NO
HOSTNAME_DNS_FREQUENCY = 20 min
IFC_SCAN_FREQUENCY = 15 min
DYNDNS_FREQUENCY = 7 min
USE_STUN = YES
STUN_FREQUENCY = 5 min
STUN_SERVERS = stun.gnunet.org stun.services.mozilla.com:3478 stun.ekiga.net:3478
STUN_STALE = 60 min

[peerstore]
IMMEDIATE_START = YES
USE_INCLUDED_HELLOS = YES
HOSTNAME = localhost
BINARY = gnunet-service-peerstore
UNIXPATH = $GNUNET_RUNTIME_DIR/gnunet-service-peerstore.sock
UNIX_MATCH_UID = NO
UNIX_MATCH_GID = YES
DATABASE = sqlite

[peerstore-sqlite]
FILENAME = $GNUNET_DATA_HOME/peerstore/sqlite.db

[resolver]
START_ON_DEMAND = YES
HOSTNAME = localhost
BINARY = gnunet-service-resolver
ACCEPT_FROM = 127.0.0.1;
ACCEPT_FROM6 = ::1;
UNIXPATH = $GNUNET_RUNTIME_DIR/gnunet-service-resolver.sock
UNIX_MATCH_UID = NO
UNIX_MATCH_GID = NO

[statistics]
START_ON_DEMAND = YES
HOSTNAME = localhost
BINARY = gnunet-service-statistics
ACCEPT_FROM = 127.0.0.1;
ACCEPT_FROM6 = ::1;
UNIXPATH = $GNUNET_RUNTIME_DIR/gnunet-service-statistics.sock
UNIX_MATCH_UID = NO
UNIX_MATCH_GID = YES
DATABASE = $GNUNET_DATA_HOME/statistics.dat

[transport]
START_ON_DEMAND = YES
HOSTNAME = localhost
BINARY = gnunet-service-transport
ACCEPT_FROM = 127.0.0.1;
ACCEPT_FROM6 = ::1;
UNIXPATH = $GNUNET_RUNTIME_DIR/gnunet-service-transport.sock

[communicator-tcp]
BINDTO = 2086
DISABLE_V6 = YES
BINARY = gnunet-communicator-tcp
IMMEDIATE_START = YES

[communicator-udp]
BINARY = gnunet-communicator-udp
BINDTO = 2086
DISABLE_V6 = YES
IMMEDIATE_START = YES
DISABLE_BROADCAST = YES

[PEER]
PRIVATE_KEY = $GNUNET_DATA_HOME/private_key.ecc
SYSTEM_TYPE = UNKNOWN

[PATHS]
GNUNET_HOME = home
GNUNET_DATA_HOME = $GNUNET_HOME/data
GNUNET_CONFIG_HOME = $GNUNET_HOME/config
GNUNET_CACHE_HOME = $GNUNET_HOME/cache
GNUNET_RUNTIME_DIR = cache/gnunet-system-runtime
GNUNET_USER_RUNTIME_DIR = cache/gnunet-runtime
GNUNET_TMP = cache

